version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db