version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - .env

  webserver:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api

  webserver-dev:
    build:
      context: ./webapp
      dockerfile: Dockerfile-dev
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db
