version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - app

  nginx-dev:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-development.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  web:
    build: ./chlorine-web
    ports:
      - "3000:3000"
