# Build web application
FROM node:21-slim AS build-stage
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /webapp

COPY package*.json /webapp/
RUN pnpm install
COPY . /webapp/
RUN pnpm build

# Use nginx to serve web application
FROM nginx:1.17

COPY --from=build-stage /webapp/dist/ /etc/nginx/html/
COPY config/nginx-development.conf /etc/nginx/nginx.conf
