name: Build UI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image for UI server
        run: docker build webapp/ --tag chlorine-web:$(date +%s)
