name: Build Server Container

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image for Chlorine server
        run: docker build . --tag chlorine:$(date +%s)
